name: extension tasks

on:
  push:
    branches:
    - main
    tags:
    - "v*"

jobs:
  prospector:
    uses: nzbgetcom/nzbget-extensions/.github/workflows/prospector.yml@main

  manifest:
    uses: nzbgetcom/nzbget-extensions/.github/workflows/manifest.yml@main

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [prospector, manifest]
    uses: nzbgetcom/nzbget-extensions/.github/workflows/extension-release.yml@main
    with:
      release-file-list: main.py manifest.json
      release-file-name: NZBClient_Notifier
      release-dir: NZBClient_Notifier
